<?php

use Illuminate\Database\Seeder;

class AnalysisElementsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('analysis_elements')->delete();
        
        \DB::table('analysis_elements')->insert(array (
            0 => 
            array (
                'id' => '1',
                'analyte_id' => '10',
                'decimal_places' => '2',
                'reporting_symbol' => '<',
                'reporting_unit' => 'mS/cm',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '1',
                'show_on_report' => '1',
                'created_at' => '2020-06-26 12:40:55.057',
                'updated_at' => '2020-07-16 18:19:17.390',
                'equipment_id' => '3',
                'method' => '1',
                'is_manual' => '0',
                'operator_id' => '2',
                'significant_figures' => NULL,
                'lod' => NULL,
                'hod' => NULL,
                'level' => '1',
            ),
            1 => 
            array (
                'id' => '2',
                'analyte_id' => '2',
                'decimal_places' => '2',
                'reporting_symbol' => '<',
                'reporting_unit' => 'cfu/100 ml',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '1',
                'show_on_report' => '1',
                'created_at' => '2020-06-29 02:37:27.413',
                'updated_at' => '2020-07-16 18:20:41.920',
                'equipment_id' => '2',
                'method' => '7',
                'is_manual' => '1',
                'operator_id' => '1',
                'significant_figures' => NULL,
                'lod' => NULL,
                'hod' => NULL,
                'level' => '6',
            ),
            2 => 
            array (
                'id' => '3',
                'analyte_id' => '3',
                'decimal_places' => '2',
                'reporting_symbol' => '>',
                'reporting_unit' => 'EC',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '2',
                'show_on_report' => '1',
                'created_at' => '2020-06-29 02:39:14.710',
                'updated_at' => '2020-07-01 05:55:33.733',
                'equipment_id' => '2',
                'method' => '4',
                'is_manual' => '1',
                'operator_id' => NULL,
                'significant_figures' => NULL,
                'lod' => NULL,
                'hod' => NULL,
                'level' => '1',
            ),
            3 => 
            array (
                'id' => '4',
                'analyte_id' => '16',
                'decimal_places' => '2',
                'reporting_symbol' => '>',
                'reporting_unit' => '1',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '3',
                'show_on_report' => '1',
                'created_at' => '2020-06-29 06:26:02.060',
                'updated_at' => '2020-06-29 06:26:02.060',
                'equipment_id' => '2',
                'method' => '5',
                'is_manual' => '1',
                'operator_id' => NULL,
                'significant_figures' => NULL,
                'lod' => NULL,
                'hod' => NULL,
                'level' => '1',
            ),
            4 => 
            array (
                'id' => '5',
                'analyte_id' => '4',
                'decimal_places' => '2',
                'reporting_symbol' => '<',
                'reporting_unit' => 'g/ml',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '4',
                'show_on_report' => '1',
                'created_at' => '2020-06-29 11:17:49.820',
                'updated_at' => '2020-07-16 18:23:47.220',
                'equipment_id' => '3',
                'method' => '1',
                'is_manual' => '1',
                'operator_id' => '2',
                'significant_figures' => '3.0',
                'lod' => '0.001',
                'hod' => NULL,
                'level' => '2',
            ),
            5 => 
            array (
                'id' => '6',
                'analyte_id' => '18',
                'decimal_places' => '2',
                'reporting_symbol' => '>',
                'reporting_unit' => 'cfu/25g',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '4',
                'show_on_report' => '1',
                'created_at' => '2020-06-29 11:18:20.607',
                'updated_at' => '2020-07-16 18:23:47.187',
                'equipment_id' => '2',
                'method' => '6',
                'is_manual' => '1',
                'operator_id' => '1',
                'significant_figures' => '4.0',
                'lod' => '5.0000000000000003E-2',
                'hod' => NULL,
                'level' => '1',
            ),
            6 => 
            array (
                'id' => '7',
                'analyte_id' => '611',
                'decimal_places' => '3',
                'reporting_symbol' => '<',
                'reporting_unit' => 'g/ml',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '5',
                'show_on_report' => '1',
                'created_at' => '2020-06-29 11:20:14.693',
                'updated_at' => '2020-07-16 18:14:43.537',
                'equipment_id' => '3',
                'method' => '4',
                'is_manual' => '1',
                'operator_id' => '3',
                'significant_figures' => '3.0',
                'lod' => '130.0',
                'hod' => NULL,
                'level' => '1',
            ),
            7 => 
            array (
                'id' => '10002',
                'analyte_id' => '20002',
                'decimal_places' => '5',
                'reporting_symbol' => NULL,
                'reporting_unit' => NULL,
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '10003',
                'show_on_report' => '1',
                'created_at' => '2020-06-30 08:21:15.670',
                'updated_at' => '2020-07-13 17:08:10.860',
                'equipment_id' => '1004',
                'method' => '9',
                'is_manual' => '1',
                'operator_id' => '2',
                'significant_figures' => NULL,
                'lod' => NULL,
                'hod' => NULL,
                'level' => '1',
            ),
            8 => 
            array (
                'id' => '10003',
                'analyte_id' => '46',
                'decimal_places' => '3',
                'reporting_symbol' => NULL,
                'reporting_unit' => 'TCU',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '10003',
                'show_on_report' => '1',
                'created_at' => '2020-07-13 19:46:28.060',
                'updated_at' => '2020-07-13 19:46:28.060',
                'equipment_id' => '1003',
                'method' => '1',
                'is_manual' => '1',
                'operator_id' => '3',
                'significant_figures' => NULL,
                'lod' => NULL,
                'hod' => NULL,
                'level' => '2',
            ),
            9 => 
            array (
                'id' => '10004',
                'analyte_id' => '5',
                'decimal_places' => '2',
                'reporting_symbol' => NULL,
                'reporting_unit' => 'cfu',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '1',
                'show_on_report' => '1',
                'created_at' => '2020-07-16 00:26:25.447',
                'updated_at' => '2020-07-16 18:19:18.913',
                'equipment_id' => '3',
                'method' => '1',
                'is_manual' => '1',
                'operator_id' => '2',
                'significant_figures' => '4.0',
                'lod' => '1.0',
                'hod' => NULL,
                'level' => '2',
            ),
            10 => 
            array (
                'id' => '10005',
                'analyte_id' => '1',
                'decimal_places' => '5',
                'reporting_symbol' => NULL,
                'reporting_unit' => 'mg/kg',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '1',
                'show_on_report' => '1',
                'created_at' => '2020-07-16 00:58:26.517',
                'updated_at' => '2020-07-16 18:20:44.203',
                'equipment_id' => '2',
                'method' => '4',
                'is_manual' => '1',
                'operator_id' => '1',
                'significant_figures' => '4.0',
                'lod' => '4.0000000000000002E-4',
                'hod' => NULL,
                'level' => '4',
            ),
            11 => 
            array (
                'id' => '10006',
                'analyte_id' => '6',
                'decimal_places' => '3',
                'reporting_symbol' => '<',
                'reporting_unit' => '5g',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '1',
                'show_on_report' => '1',
                'created_at' => '2020-07-16 01:54:39.600',
                'updated_at' => '2020-07-16 18:20:40.593',
                'equipment_id' => '2',
                'method' => '5',
                'is_manual' => '1',
                'operator_id' => '2',
                'significant_figures' => '7.0',
                'lod' => '8.9999999999999997E-2',
                'hod' => NULL,
                'level' => '7',
            ),
            12 => 
            array (
                'id' => '10007',
                'analyte_id' => '27',
                'decimal_places' => '2',
                'reporting_symbol' => NULL,
                'reporting_unit' => 'g',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '1',
                'show_on_report' => '1',
                'created_at' => '2020-07-16 03:35:15.107',
                'updated_at' => '2020-07-16 18:20:43.120',
                'equipment_id' => '3',
                'method' => '7',
                'is_manual' => '1',
                'operator_id' => '2',
                'significant_figures' => '4.0',
                'lod' => '0.56399999999999995',
                'hod' => NULL,
                'level' => '5',
            ),
            13 => 
            array (
                'id' => '10008',
                'analyte_id' => '4',
                'decimal_places' => '4',
                'reporting_symbol' => '>',
                'reporting_unit' => 'TCU',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '1',
                'show_on_report' => '1',
                'created_at' => '2020-07-16 03:49:31.397',
                'updated_at' => '2020-07-16 18:20:44.233',
                'equipment_id' => '3',
                'method' => '2',
                'is_manual' => '1',
                'operator_id' => '2',
                'significant_figures' => '3.0',
                'lod' => '9.7600000000000006E-2',
                'hod' => NULL,
                'level' => '3',
            ),
            14 => 
            array (
                'id' => '10009',
                'analyte_id' => '86',
                'decimal_places' => '2',
                'reporting_symbol' => '<',
                'reporting_unit' => 'mmol',
                'non_detectable' => '0',
                'non_accredited' => '0',
                'active' => '1',
                'company_id' => '1',
                'analysis_type_id' => '10004',
                'show_on_report' => '1',
                'created_at' => '2020-07-21 15:31:01.490',
                'updated_at' => '2020-07-21 15:31:01.490',
                'equipment_id' => '2',
                'method' => '1',
                'is_manual' => '1',
                'operator_id' => '2',
                'significant_figures' => '3.0',
                'lod' => '1.0',
                'hod' => '100.0',
                'level' => '1',
            ),
        ));
        
        
    }
}