<?php

use Illuminate\Database\Seeder;

class CapturedResultsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('captured_results')->delete();
        
        \DB::table('captured_results')->insert(array (
            0 => 
            array (
                'id' => '20044',
                'sample_detail_code' => 'SAMP/000015',
                'sample_detail_id' => '30031',
                'sample_header_id' => '30016',
                'analyte_id' => '611',
                'analyte_code' => 'Free Moisture',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-14 07:53:34.633',
                'updated_at' => '2020-07-15 12:44:28.083',
                'analysis_type_id' => '5',
                'operator_id' => '3',
                'method_id' => '4',
                'machine_update_date' => NULL,
            ),
            1 => 
            array (
                'id' => '20045',
                'sample_detail_code' => 'SAMP/000015',
                'sample_detail_id' => '30031',
                'sample_header_id' => '30016',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => '20.0',
                'user_id' => '2',
                'created_at' => '2020-07-14 07:53:51.267',
                'updated_at' => '2020-07-15 12:44:28.110',
                'analysis_type_id' => '4',
                'operator_id' => '2',
                'method_id' => '1',
                'machine_update_date' => '2020-07-14 14:15:43.000',
            ),
            2 => 
            array (
                'id' => '20046',
                'sample_detail_code' => 'SAMP/000015',
                'sample_detail_id' => '30031',
                'sample_header_id' => '30016',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-14 07:53:51.337',
                'updated_at' => '2020-07-15 12:44:28.143',
                'analysis_type_id' => '4',
                'operator_id' => '1',
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            3 => 
            array (
                'id' => '20047',
                'sample_detail_code' => 'SAMP/000014',
                'sample_detail_id' => '30030',
                'sample_header_id' => '30016',
                'analyte_id' => '20002',
                'analyte_code' => 'D20',
                'equipment_id' => '1004',
                'result' => '345.0',
                'user_id' => '2',
                'created_at' => '2020-07-14 07:54:08.740',
                'updated_at' => '2020-07-15 22:39:25.507',
                'analysis_type_id' => '10003',
                'operator_id' => '2',
                'method_id' => '9',
                'machine_update_date' => NULL,
            ),
            4 => 
            array (
                'id' => '20048',
                'sample_detail_code' => 'SAMP/000014',
                'sample_detail_id' => '30030',
                'sample_header_id' => '30016',
                'analyte_id' => '46',
                'analyte_code' => 'TDS',
                'equipment_id' => '1003',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-14 07:54:08.807',
                'updated_at' => '2020-07-15 22:39:25.563',
                'analysis_type_id' => '10003',
                'operator_id' => '3',
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            5 => 
            array (
                'id' => '20049',
                'sample_detail_code' => 'SAMP/000016',
                'sample_detail_id' => '30032',
                'sample_header_id' => '30017',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => '0.1215412',
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.193',
                'updated_at' => '2020-07-15 20:17:13.100',
                'analysis_type_id' => '4',
                'operator_id' => '2',
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            6 => 
            array (
                'id' => '20050',
                'sample_detail_code' => 'SAMP/000016',
                'sample_detail_id' => '30032',
                'sample_header_id' => '30017',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.257',
                'updated_at' => '2020-07-15 20:17:13.127',
                'analysis_type_id' => '4',
                'operator_id' => '1',
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            7 => 
            array (
                'id' => '20051',
                'sample_detail_code' => 'SAMP/000017',
                'sample_detail_id' => '30033',
                'sample_header_id' => '30017',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.297',
                'updated_at' => '2020-07-15 17:39:45.297',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            8 => 
            array (
                'id' => '20052',
                'sample_detail_code' => 'SAMP/000017',
                'sample_detail_id' => '30033',
                'sample_header_id' => '30017',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.347',
                'updated_at' => '2020-07-15 17:39:45.347',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            9 => 
            array (
                'id' => '20053',
                'sample_detail_code' => 'SAMP/000018',
                'sample_detail_id' => '30034',
                'sample_header_id' => '30017',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => '123.0',
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.413',
                'updated_at' => '2020-07-15 20:16:40.400',
                'analysis_type_id' => '4',
                'operator_id' => '2',
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            10 => 
            array (
                'id' => '20054',
                'sample_detail_code' => 'SAMP/000018',
                'sample_detail_id' => '30034',
                'sample_header_id' => '30017',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.477',
                'updated_at' => '2020-07-15 20:16:40.443',
                'analysis_type_id' => '4',
                'operator_id' => '1',
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            11 => 
            array (
                'id' => '20055',
                'sample_detail_code' => 'SAMP/000019',
                'sample_detail_id' => '30035',
                'sample_header_id' => '30017',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.530',
                'updated_at' => '2020-07-15 17:39:45.530',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            12 => 
            array (
                'id' => '20056',
                'sample_detail_code' => 'SAMP/000019',
                'sample_detail_id' => '30035',
                'sample_header_id' => '30017',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.573',
                'updated_at' => '2020-07-15 17:39:45.573',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            13 => 
            array (
                'id' => '20057',
                'sample_detail_code' => 'SAMP/000020',
                'sample_detail_id' => '30036',
                'sample_header_id' => '30017',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.640',
                'updated_at' => '2020-07-15 17:39:45.640',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            14 => 
            array (
                'id' => '20058',
                'sample_detail_code' => 'SAMP/000020',
                'sample_detail_id' => '30036',
                'sample_header_id' => '30017',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.697',
                'updated_at' => '2020-07-15 17:39:45.697',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            15 => 
            array (
                'id' => '20059',
                'sample_detail_code' => 'SAMP/000021',
                'sample_detail_id' => '30037',
                'sample_header_id' => '30017',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.773',
                'updated_at' => '2020-07-15 17:39:45.773',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            16 => 
            array (
                'id' => '20060',
                'sample_detail_code' => 'SAMP/000021',
                'sample_detail_id' => '30037',
                'sample_header_id' => '30017',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.833',
                'updated_at' => '2020-07-15 17:39:45.833',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            17 => 
            array (
                'id' => '20061',
                'sample_detail_code' => 'SAMP/000022',
                'sample_detail_id' => '30038',
                'sample_header_id' => '30017',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.887',
                'updated_at' => '2020-07-15 17:39:45.887',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            18 => 
            array (
                'id' => '20062',
                'sample_detail_code' => 'SAMP/000022',
                'sample_detail_id' => '30038',
                'sample_header_id' => '30017',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.940',
                'updated_at' => '2020-07-15 17:39:45.940',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            19 => 
            array (
                'id' => '20063',
                'sample_detail_code' => 'SAMP/000023',
                'sample_detail_id' => '30039',
                'sample_header_id' => '30017',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => '0.0123456789',
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:45.993',
                'updated_at' => '2020-07-16 18:22:39.380',
                'analysis_type_id' => '4',
                'operator_id' => '2',
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            20 => 
            array (
                'id' => '20064',
                'sample_detail_code' => 'SAMP/000023',
                'sample_detail_id' => '30039',
                'sample_header_id' => '30017',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:46.103',
                'updated_at' => '2020-07-16 18:22:39.413',
                'analysis_type_id' => '4',
                'operator_id' => '1',
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            21 => 
            array (
                'id' => '20065',
                'sample_detail_code' => 'SAMP/000024',
                'sample_detail_id' => '30040',
                'sample_header_id' => '30017',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:46.157',
                'updated_at' => '2020-07-15 17:39:46.157',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            22 => 
            array (
                'id' => '20066',
                'sample_detail_code' => 'SAMP/000024',
                'sample_detail_id' => '30040',
                'sample_header_id' => '30017',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:46.203',
                'updated_at' => '2020-07-15 17:39:46.203',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            23 => 
            array (
                'id' => '20067',
                'sample_detail_code' => 'SAMP/000025',
                'sample_detail_id' => '30041',
                'sample_header_id' => '30017',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:46.257',
                'updated_at' => '2020-07-15 17:39:46.257',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            24 => 
            array (
                'id' => '20068',
                'sample_detail_code' => 'SAMP/000025',
                'sample_detail_id' => '30041',
                'sample_header_id' => '30017',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:46.313',
                'updated_at' => '2020-07-15 17:39:46.313',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            25 => 
            array (
                'id' => '20069',
                'sample_detail_code' => 'SAMP/000026',
                'sample_detail_id' => '30042',
                'sample_header_id' => '30017',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:46.363',
                'updated_at' => '2020-07-15 17:39:46.363',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            26 => 
            array (
                'id' => '20070',
                'sample_detail_code' => 'SAMP/000026',
                'sample_detail_id' => '30042',
                'sample_header_id' => '30017',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:39:46.450',
                'updated_at' => '2020-07-15 17:39:46.450',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            27 => 
            array (
                'id' => '20071',
                'sample_detail_code' => 'SAMP/000017',
                'sample_detail_id' => '30033',
                'sample_header_id' => '30017',
                'analyte_id' => '611',
                'analyte_code' => 'Free Moisture',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:40:45.173',
                'updated_at' => '2020-07-15 17:40:45.173',
                'analysis_type_id' => '5',
                'operator_id' => NULL,
                'method_id' => '4',
                'machine_update_date' => NULL,
            ),
            28 => 
            array (
                'id' => '20072',
                'sample_detail_code' => 'SAMP/000018',
                'sample_detail_id' => '30034',
                'sample_header_id' => '30017',
                'analyte_id' => '611',
                'analyte_code' => 'Free Moisture',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:40:45.217',
                'updated_at' => '2020-07-15 20:16:40.477',
                'analysis_type_id' => '5',
                'operator_id' => '3',
                'method_id' => '4',
                'machine_update_date' => NULL,
            ),
            29 => 
            array (
                'id' => '20073',
                'sample_detail_code' => 'SAMP/000019',
                'sample_detail_id' => '30035',
                'sample_header_id' => '30017',
                'analyte_id' => '611',
                'analyte_code' => 'Free Moisture',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-15 17:40:45.293',
                'updated_at' => '2020-07-15 17:40:45.293',
                'analysis_type_id' => '5',
                'operator_id' => NULL,
                'method_id' => '4',
                'machine_update_date' => NULL,
            ),
            30 => 
            array (
                'id' => '20074',
                'sample_detail_code' => 'SAMP/000027',
                'sample_detail_id' => '30043',
                'sample_header_id' => '30018',
                'analyte_id' => '611',
                'analyte_code' => 'Free Moisture',
                'equipment_id' => '3',
                'result' => '123.0',
                'user_id' => '2',
                'created_at' => '2020-07-16 18:03:23.947',
                'updated_at' => '2020-07-16 18:11:34.993',
                'analysis_type_id' => '5',
                'operator_id' => '3',
                'method_id' => '4',
                'machine_update_date' => NULL,
            ),
            31 => 
            array (
                'id' => '20075',
                'sample_detail_code' => 'SAMP/000033',
                'sample_detail_id' => '30049',
                'sample_header_id' => '30023',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => '1.2121212123319999E-2',
                'user_id' => '2',
                'created_at' => '2020-07-21 12:59:26.117',
                'updated_at' => '2020-07-21 13:20:08.143',
                'analysis_type_id' => '4',
                'operator_id' => '2',
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            32 => 
            array (
                'id' => '20076',
                'sample_detail_code' => 'SAMP/000033',
                'sample_detail_id' => '30049',
                'sample_header_id' => '30023',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-21 12:59:26.233',
                'updated_at' => '2020-07-21 13:14:45.603',
                'analysis_type_id' => '4',
                'operator_id' => '1',
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            33 => 
            array (
                'id' => '20077',
                'sample_detail_code' => 'SAMP/000034',
                'sample_detail_id' => '30050',
                'sample_header_id' => '30023',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-21 12:59:26.330',
                'updated_at' => '2020-07-21 12:59:26.330',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            34 => 
            array (
                'id' => '20078',
                'sample_detail_code' => 'SAMP/000034',
                'sample_detail_id' => '30050',
                'sample_header_id' => '30023',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-21 12:59:26.417',
                'updated_at' => '2020-07-21 12:59:26.417',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            35 => 
            array (
                'id' => '20079',
                'sample_detail_code' => 'SAMP/000035',
                'sample_detail_id' => '30051',
                'sample_header_id' => '30023',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-21 12:59:26.553',
                'updated_at' => '2020-07-21 12:59:26.553',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            36 => 
            array (
                'id' => '20080',
                'sample_detail_code' => 'SAMP/000035',
                'sample_detail_id' => '30051',
                'sample_header_id' => '30023',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-21 12:59:26.677',
                'updated_at' => '2020-07-21 12:59:26.677',
                'analysis_type_id' => '4',
                'operator_id' => NULL,
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            37 => 
            array (
                'id' => '20081',
                'sample_detail_code' => 'SAMP/000033',
                'sample_detail_id' => '30049',
                'sample_header_id' => '30023',
                'analyte_id' => '611',
                'analyte_code' => 'Free Moisture',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-21 13:11:16.607',
                'updated_at' => '2020-07-21 13:14:45.660',
                'analysis_type_id' => '5',
                'operator_id' => '3',
                'method_id' => '4',
                'machine_update_date' => NULL,
            ),
            38 => 
            array (
                'id' => '20082',
                'sample_detail_code' => 'SAMP/000036',
                'sample_detail_id' => '30052',
                'sample_header_id' => '30024',
                'analyte_id' => '86',
                'analyte_code' => 'FC',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-21 15:42:36.157',
                'updated_at' => '2020-07-21 15:42:36.157',
                'analysis_type_id' => '10004',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            39 => 
            array (
                'id' => '20083',
                'sample_detail_code' => 'SAMP/000037',
                'sample_detail_id' => '30053',
                'sample_header_id' => '30024',
                'analyte_id' => '86',
                'analyte_code' => 'FC',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-21 15:42:36.283',
                'updated_at' => '2020-07-21 15:42:36.283',
                'analysis_type_id' => '10004',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            40 => 
            array (
                'id' => '20084',
                'sample_detail_code' => 'SAMP/000038',
                'sample_detail_id' => '30054',
                'sample_header_id' => '30024',
                'analyte_id' => '86',
                'analyte_code' => 'FC',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-21 15:42:36.430',
                'updated_at' => '2020-07-21 15:42:36.430',
                'analysis_type_id' => '10004',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            41 => 
            array (
                'id' => '20085',
                'sample_detail_code' => 'SAMP/000039',
                'sample_detail_id' => '30055',
                'sample_header_id' => '30024',
                'analyte_id' => '86',
                'analyte_code' => 'FC',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-21 15:42:36.557',
                'updated_at' => '2020-07-21 15:42:36.557',
                'analysis_type_id' => '10004',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            42 => 
            array (
                'id' => '20086',
                'sample_detail_code' => 'SAMP/000040',
                'sample_detail_id' => '30056',
                'sample_header_id' => '30024',
                'analyte_id' => '86',
                'analyte_code' => 'FC',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-21 15:42:36.680',
                'updated_at' => '2020-07-21 15:42:36.680',
                'analysis_type_id' => '10004',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            43 => 
            array (
                'id' => '20087',
                'sample_detail_code' => 'SAMP/000041',
                'sample_detail_id' => '30057',
                'sample_header_id' => '30024',
                'analyte_id' => '86',
                'analyte_code' => 'FC',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '2',
                'created_at' => '2020-07-21 15:42:36.807',
                'updated_at' => '2020-07-21 15:42:36.807',
                'analysis_type_id' => '10004',
                'operator_id' => NULL,
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            44 => 
            array (
                'id' => '20088',
                'sample_detail_code' => 'SAMP/000080',
                'sample_detail_id' => '30095',
                'sample_header_id' => '30026',
                'analyte_id' => '4',
                'analyte_code' => 'Na',
                'equipment_id' => '3',
                'result' => '23.0',
                'user_id' => '7',
                'created_at' => '2020-08-05 09:53:31.970',
                'updated_at' => '2020-08-05 10:01:25.770',
                'analysis_type_id' => '4',
                'operator_id' => '2',
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
            45 => 
            array (
                'id' => '20089',
                'sample_detail_code' => 'SAMP/000080',
                'sample_detail_id' => '30095',
                'sample_header_id' => '30026',
                'analyte_id' => '18',
                'analyte_code' => 'Cl',
                'equipment_id' => '2',
                'result' => NULL,
                'user_id' => '7',
                'created_at' => '2020-08-05 09:53:32.120',
                'updated_at' => '2020-08-05 09:55:14.693',
                'analysis_type_id' => '4',
                'operator_id' => '1',
                'method_id' => '6',
                'machine_update_date' => NULL,
            ),
            46 => 
            array (
                'id' => '20090',
                'sample_detail_code' => 'SAMP/000080',
                'sample_detail_id' => '30095',
                'sample_header_id' => '30026',
                'analyte_id' => '611',
                'analyte_code' => 'Free Moisture',
                'equipment_id' => '3',
                'result' => NULL,
                'user_id' => '7',
                'created_at' => '2020-08-05 09:53:32.237',
                'updated_at' => '2020-08-05 09:55:14.743',
                'analysis_type_id' => '5',
                'operator_id' => '3',
                'method_id' => '4',
                'machine_update_date' => NULL,
            ),
            47 => 
            array (
                'id' => '20091',
                'sample_detail_code' => 'SAMP/000080',
                'sample_detail_id' => '30095',
                'sample_header_id' => '30026',
                'analyte_id' => '20002',
                'analyte_code' => 'D20',
                'equipment_id' => '1004',
                'result' => NULL,
                'user_id' => '7',
                'created_at' => '2020-08-05 09:53:32.343',
                'updated_at' => '2020-08-05 09:55:14.820',
                'analysis_type_id' => '10003',
                'operator_id' => '2',
                'method_id' => '9',
                'machine_update_date' => NULL,
            ),
            48 => 
            array (
                'id' => '20092',
                'sample_detail_code' => 'SAMP/000080',
                'sample_detail_id' => '30095',
                'sample_header_id' => '30026',
                'analyte_id' => '46',
                'analyte_code' => 'TDS',
                'equipment_id' => '1003',
                'result' => NULL,
                'user_id' => '7',
                'created_at' => '2020-08-05 09:53:32.450',
                'updated_at' => '2020-08-05 09:55:14.890',
                'analysis_type_id' => '10003',
                'operator_id' => '3',
                'method_id' => '1',
                'machine_update_date' => NULL,
            ),
        ));
        
        
    }
}