<?php

use Illuminate\Database\Seeder;

class InventorySubCategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('inventory_sub_categories')->delete();
        
        \DB::table('inventory_sub_categories')->insert(array (
            0 => 
            array (
                'id' => '1',
                'name' => 'Fine Grain Sugar.',
                'description' => 'This is sugar of the finest grain.',
                'image' => '/storage/subcategory/BQ1BfE1fZeeT3gAlMW1ef9zaa1zIcgVnA3bGfld2.jpeg',
                'inventory_category_id' => '1',
                'manufacturer' => 'Sony Sugar',
                'created_at' => '2020-04-15 18:21:30.913',
                'updated_at' => '2020-06-22 01:50:41.623',
                'minimum_level' => '1000.0',
                'unit_type' => 'kgs',
                'unit_price' => '200.0',
                'reporting_decimal_places' => '2',
                'code' => 'FGS-01',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => NULL,
                'parent_id' => NULL,
            ),
            1 => 
            array (
                'id' => '2',
                'name' => 'Classical TestTubes',
                'description' => 'Classic common test tube',
                'image' => '/storage/subcategory/gVNICmpxnSj9bSOVfefdZKVaEv5tvragbCs2SgVe.jpeg',
                'inventory_category_id' => '2',
                'manufacturer' => 'KGlass',
                'created_at' => '2020-05-25 14:06:19.910',
                'updated_at' => '2020-06-21 20:11:02.043',
                'minimum_level' => '1000.0',
            'unit_type' => 'piece(s)',
                'unit_price' => '25.0',
                'reporting_decimal_places' => '0',
                'code' => 'CT-01',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => NULL,
                'parent_id' => NULL,
            ),
            2 => 
            array (
                'id' => '10002',
                'name' => 'Brown Sugar',
                'description' => 'This is a test',
                'image' => '/storage/subcategory/NeHL1PluSajDF8XT9cBFvdmSsWiXc7JZOmSoQaac.jpeg',
                'inventory_category_id' => '1',
                'manufacturer' => 'Mumias',
                'created_at' => '2020-06-21 08:51:56.917',
                'updated_at' => '2020-06-21 08:51:56.917',
                'minimum_level' => '1500.0',
                'unit_type' => 'kgs',
                'unit_price' => '120.0',
                'reporting_decimal_places' => NULL,
                'code' => 'BS-01',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => NULL,
                'parent_id' => NULL,
            ),
            3 => 
            array (
                'id' => '10003',
                'name' => 'Jembe',
                'description' => 'used for digging',
                'image' => '/storage/subcategory/2wGbGyqeZcySl1xVxUNCPEsGpIalDhQEccER9j2J.jpeg',
                'inventory_category_id' => '10003',
                'manufacturer' => 'Jua Kali',
                'created_at' => '2020-07-06 11:41:48.523',
                'updated_at' => '2020-07-06 11:41:48.523',
                'minimum_level' => '5.0',
                'unit_type' => 'TCU',
                'unit_price' => '2500.0',
                'reporting_decimal_places' => '0',
                'code' => 'NJ0001',
                'company_id' => '1',
                'location_id' => '5',
                'parent' => NULL,
                'parent_id' => NULL,
            ),
            4 => 
            array (
                'id' => '20028',
                'name' => 'BCCB00070033/SAMP/000075',
                'description' => 'Sample for batch - BCCB00070033',
                'image' => '/images/lab-item.png',
                'inventory_category_id' => '20003',
                'manufacturer' => 'Source: Lab',
                'created_at' => '2020-07-27 02:53:16.143',
                'updated_at' => '2020-07-27 02:53:16.143',
                'minimum_level' => '0.0',
                'unit_type' => 'g',
                'unit_price' => '0.0',
                'reporting_decimal_places' => '2',
                'code' => 'LB0026',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => '\\App\\SampleDetails',
                'parent_id' => '30090',
            ),
            5 => 
            array (
                'id' => '20029',
                'name' => 'BCCB00070033/SAMP/000076',
                'description' => 'Sample for batch - BCCB00070033',
                'image' => '/images/lab-item.png',
                'inventory_category_id' => '20003',
                'manufacturer' => 'Source: Lab',
                'created_at' => '2020-07-27 02:53:16.603',
                'updated_at' => '2020-07-27 02:53:16.603',
                'minimum_level' => '0.0',
                'unit_type' => 'g',
                'unit_price' => '0.0',
                'reporting_decimal_places' => '2',
                'code' => 'LB0027',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => '\\App\\SampleDetails',
                'parent_id' => '30091',
            ),
            6 => 
            array (
                'id' => '20030',
                'name' => 'BCCB00070033/SAMP/000077',
                'description' => 'Sample for batch - BCCB00070033',
                'image' => '/images/lab-item.png',
                'inventory_category_id' => '20003',
                'manufacturer' => 'Source: Lab',
                'created_at' => '2020-07-27 02:53:17.027',
                'updated_at' => '2020-07-27 02:53:17.027',
                'minimum_level' => '0.0',
                'unit_type' => 'g',
                'unit_price' => '0.0',
                'reporting_decimal_places' => '2',
                'code' => 'LB0028',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => '\\App\\SampleDetails',
                'parent_id' => '30092',
            ),
            7 => 
            array (
                'id' => '20031',
                'name' => 'BCCB00070033/SAMP/000078',
                'description' => 'Sample for batch - BCCB00070033',
                'image' => '/images/lab-item.png',
                'inventory_category_id' => '20003',
                'manufacturer' => 'Source: Lab',
                'created_at' => '2020-07-27 02:53:17.460',
                'updated_at' => '2020-07-27 02:53:17.460',
                'minimum_level' => '0.0',
                'unit_type' => 'g',
                'unit_price' => '0.0',
                'reporting_decimal_places' => '2',
                'code' => 'LB0029',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => '\\App\\SampleDetails',
                'parent_id' => '30093',
            ),
            8 => 
            array (
                'id' => '20033',
                'name' => 'BCCB00070033/SAMP/000062',
                'description' => 'Sample for batch - BCCB00070033',
                'image' => '/images/lab-item.png',
                'inventory_category_id' => '20003',
                'manufacturer' => 'Source: Lab',
                'created_at' => '2020-07-27 02:55:29.173',
                'updated_at' => '2020-07-27 02:55:29.173',
                'minimum_level' => '0.0',
                'unit_type' => 'ppb',
                'unit_price' => '0.0',
                'reporting_decimal_places' => '2',
                'code' => 'LB0031',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => '\\App\\SampleDetails',
                'parent_id' => '30077',
            ),
            9 => 
            array (
                'id' => '20034',
                'name' => 'BCCB00070033/SAMP/000061',
                'description' => 'Sample for batch - BCCB00070033',
                'image' => '/images/lab-item.png',
                'inventory_category_id' => '20003',
                'manufacturer' => 'Source: Lab',
                'created_at' => '2020-07-27 02:56:16.313',
                'updated_at' => '2020-07-27 02:56:16.313',
                'minimum_level' => '0.0',
                'unit_type' => 'g/cm3',
                'unit_price' => '0.0',
                'reporting_decimal_places' => '2',
                'code' => 'LB0032',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => '\\App\\SampleDetails',
                'parent_id' => '30076',
            ),
            10 => 
            array (
                'id' => '20035',
                'name' => 'r1',
                'description' => 'r1',
                'image' => '/storage/subcategory/abbFN6tpOMa9ptGxo7oHNtcvU1eK6N36pkycsRQF.jpeg',
                'inventory_category_id' => '20004',
                'manufacturer' => 'Reagents',
                'created_at' => '2020-07-31 19:07:58.227',
                'updated_at' => '2020-07-31 19:07:58.227',
                'minimum_level' => '200.0',
                'unit_type' => 'g/kg',
                'unit_price' => '12.0',
                'reporting_decimal_places' => '3',
                'code' => 'LR0001',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => NULL,
                'parent_id' => NULL,
            ),
            11 => 
            array (
                'id' => '20036',
                'name' => 'r2',
                'description' => 'r2',
                'image' => '/storage/subcategory/abbFN6tpOMa9ptGxo7oHNtcvU1eK6N36pkycsRQF.jpeg',
                'inventory_category_id' => '20004',
                'manufacturer' => 'Reagents',
                'created_at' => '2020-07-31 19:07:58.227',
                'updated_at' => '2020-07-31 19:11:45.523',
                'minimum_level' => '300.0',
                'unit_type' => 'g/cm3',
                'unit_price' => '45.0',
                'reporting_decimal_places' => NULL,
                'code' => 'LR0001',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => NULL,
                'parent_id' => NULL,
            ),
            12 => 
            array (
                'id' => '20037',
                'name' => 'BCCB00070034/SAMP/000080',
                'description' => 'Sample for batch - BCCB00070034',
                'image' => '/images/lab-item.png',
                'inventory_category_id' => '20003',
                'manufacturer' => 'Source: Lab',
                'created_at' => '2020-08-05 09:52:04.947',
                'updated_at' => '2020-08-05 09:52:04.947',
                'minimum_level' => '0.0',
                'unit_type' => '5 gm',
                'unit_price' => '0.0',
                'reporting_decimal_places' => '2',
                'code' => 'LB0033',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => '\\App\\SampleDetails',
                'parent_id' => '30095',
            ),
            13 => 
            array (
                'id' => '20038',
                'name' => 'BCCB00070029/SAMP/000081',
                'description' => 'Sample for batch - BCCB00070029',
                'image' => '/images/lab-item.png',
                'inventory_category_id' => '20003',
                'manufacturer' => 'Source: Lab',
                'created_at' => '2020-08-05 10:02:31.487',
                'updated_at' => '2020-08-05 10:02:31.487',
                'minimum_level' => '0.0',
                'unit_type' => '100 ml',
                'unit_price' => '0.0',
                'reporting_decimal_places' => '2',
                'code' => 'LB0034',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => '\\App\\SampleDetails',
                'parent_id' => '30096',
            ),
            14 => 
            array (
                'id' => '20044',
                'name' => 'BCCB00070035/SAMP/000087',
                'description' => 'Sample for batch - BCCB00070035',
                'image' => '/images/lab-item.png',
                'inventory_category_id' => '20003',
                'manufacturer' => 'Source: Lab',
                'created_at' => '2020-08-05 11:15:27.817',
                'updated_at' => '2020-08-05 11:15:27.817',
                'minimum_level' => '0.0',
            'unit_type' => 'Piece(s)',
                'unit_price' => '0.0',
                'reporting_decimal_places' => '2',
                'code' => 'LB0040',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => '\\App\\SampleDetails',
                'parent_id' => '30102',
            ),
            15 => 
            array (
                'id' => '20045',
                'name' => 'BCCB00070035/SAMP/000088',
                'description' => 'Sample for batch - BCCB00070035',
                'image' => '/images/lab-item.png',
                'inventory_category_id' => '20003',
                'manufacturer' => 'Source: Lab',
                'created_at' => '2020-08-05 11:16:34.383',
                'updated_at' => '2020-08-05 11:16:34.383',
                'minimum_level' => '0.0',
            'unit_type' => 'Piece(s)',
                'unit_price' => '0.0',
                'reporting_decimal_places' => '2',
                'code' => 'LB0041',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => '\\App\\SampleDetails',
                'parent_id' => '30103',
            ),
            16 => 
            array (
                'id' => '20046',
                'name' => 'BCCB00070035/SAMP/000089',
                'description' => 'Sample for batch - BCCB00070035',
                'image' => '/images/lab-item.png',
                'inventory_category_id' => '20003',
                'manufacturer' => 'Source: Lab',
                'created_at' => '2020-08-05 11:16:34.853',
                'updated_at' => '2020-08-05 11:16:34.853',
                'minimum_level' => '0.0',
            'unit_type' => 'Piece(s)',
                'unit_price' => '0.0',
                'reporting_decimal_places' => '2',
                'code' => 'LB0042',
                'company_id' => '1',
                'location_id' => '3',
                'parent' => '\\App\\SampleDetails',
                'parent_id' => '30104',
            ),
            17 => 
            array (
                'id' => '20047',
                'name' => 'Fine Sugar',
                'description' => 'All about the sugar',
                'image' => '/storage/subcategory/wysUV5YZfCdO6ZEUGR9XRIAzcigWg6XQDEqd2GNh.jpeg',
                'inventory_category_id' => '10002',
                'manufacturer' => 'Sony Sugar',
                'created_at' => '2020-08-06 18:22:11.247',
                'updated_at' => '2020-08-06 18:22:11.247',
                'minimum_level' => '1000.0',
                'unit_type' => 'kg',
                'unit_price' => '178.0',
                'reporting_decimal_places' => '1',
                'code' => 'SF0001',
                'company_id' => '1',
                'location_id' => '5',
                'parent' => NULL,
                'parent_id' => NULL,
            ),
        ));
        
        
    }
}