<?php

use Illuminate\Database\Seeder;

class RequestEntitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('request_entities')->delete();
        
        \DB::table('request_entities')->insert(array (
            0 => 
            array (
                'id' => '10033',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'MR0017',
                'status' => 'Approval Complete',
                'due_date' => '2020-08-11',
                'parent_request' => NULL,
                'parent_request_id' => NULL,
                'request_type' => 'Material Requisition',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'Classical TestTubes(872), Fine Grain Sugar.(200), Brown Sugar(150), r1(123), r2(234)',
                'created_at' => '2020-08-04 16:45:15.297',
                'updated_at' => '2020-08-04 16:45:43.710',
                'net_value' => '91806',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => NULL,
            ),
            1 => 
            array (
                'id' => '10034',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'RFQ0011',
                'status' => 'Approval Complete',
                'due_date' => '2020-08-11',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10033',
                'request_type' => 'Request for Quotation',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'Classical TestTubes(872), Fine Grain Sugar.(200), Brown Sugar(150), r1(123), r2(234)',
                'created_at' => '2020-08-04 16:46:01.757',
                'updated_at' => '2020-08-04 17:14:14.880',
                'net_value' => '235400',
                'submission_deadline' => '2020-09-11 03:00:00.000',
                'supplier_id' => NULL,
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10033',
            ),
            2 => 
            array (
                'id' => '10035',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'MI0004',
                'status' => 'Awaiting User Reception',
                'due_date' => '2020-08-11',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10033',
                'request_type' => 'Material Issuance',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'Classical TestTubes(872), Fine Grain Sugar.(200), Brown Sugar(150), r1(123), r2(234)',
                'created_at' => '2020-08-04 16:46:02.380',
                'updated_at' => '2020-08-05 10:32:20.360',
                'net_value' => '91806',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10033',
            ),
            3 => 
            array (
                'id' => '10036',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'PO0008',
                'status' => 'Purchase Order Sent',
                'due_date' => '2020-08-11',
                'parent_request' => 'Request for Quotation',
                'parent_request_id' => '10034',
                'request_type' => 'Purchase Orders',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'Fine Grain Sugar.(789)',
                'created_at' => '2020-08-04 17:14:44.750',
                'updated_at' => '2020-08-04 18:18:55.013',
                'net_value' => '163400',
                'submission_deadline' => '2020-09-11 03:00:00.000',
                'supplier_id' => '2',
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10033',
            ),
            4 => 
            array (
                'id' => '10037',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'PO0009',
                'status' => 'Purchase Order Sent',
                'due_date' => '2020-08-04',
                'parent_request' => 'Request for Quotation',
                'parent_request_id' => '10034',
                'request_type' => 'Purchase Orders',
                'approval_count' => '0',
                'required_approvals' => '4',
                'created_by' => '7',
            'description' => 'Brown Sugar(450)',
                'created_at' => '2020-08-04 17:14:45.540',
                'updated_at' => '2020-08-04 17:28:11.130',
                'net_value' => '72000',
                'submission_deadline' => '2020-09-11 03:00:00.000',
                'supplier_id' => '3',
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10033',
            ),
            5 => 
            array (
                'id' => '10038',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'GR0005',
                'status' => 'Completed',
                'due_date' => '2020-08-04',
                'parent_request' => 'Purchase Orders',
                'parent_request_id' => '10037',
                'request_type' => 'Goods Receipt',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'Brown Sugar(450)',
                'created_at' => '2020-08-04 18:33:49.717',
                'updated_at' => '2020-08-04 20:36:37.003',
                'net_value' => '72000',
                'submission_deadline' => '2020-09-11 03:00:00.000',
                'supplier_id' => '3',
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10033',
            ),
            6 => 
            array (
                'id' => '10039',
                'priority' => 'High',
                'currency' => '14',
                'request_code' => 'MR0018',
                'status' => 'Rejected',
                'due_date' => '2020-08-11',
                'parent_request' => NULL,
                'parent_request_id' => NULL,
                'request_type' => 'Material Requisition',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'Classical TestTubes(20)',
                'created_at' => '2020-08-04 20:52:00.767',
                'updated_at' => '2020-08-04 21:11:21.627',
                'net_value' => '500',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => NULL,
            ),
            7 => 
            array (
                'id' => '10040',
                'priority' => 'High',
                'currency' => '14',
                'request_code' => 'MR0019',
                'status' => 'Approval Complete',
                'due_date' => '2020-08-12',
                'parent_request' => NULL,
                'parent_request_id' => NULL,
                'request_type' => 'Material Requisition',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(300)',
                'created_at' => '2020-08-05 10:06:08.633',
                'updated_at' => '2020-08-05 10:06:24.167',
                'net_value' => '7500',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => NULL,
            ),
            8 => 
            array (
                'id' => '10041',
                'priority' => 'High',
                'currency' => '14',
                'request_code' => 'MI0005',
                'status' => 'Awaiting User Reception',
                'due_date' => '2020-08-12',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10040',
                'request_type' => 'Material Issuance',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(300)',
                'created_at' => '2020-08-05 10:06:32.157',
                'updated_at' => '2020-08-05 10:06:32.257',
                'net_value' => '7500',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => '2',
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10040',
            ),
            9 => 
            array (
                'id' => '10042',
                'priority' => 'High',
                'currency' => '14',
                'request_code' => 'MI0006',
                'status' => 'Awaiting User Reception',
                'due_date' => '2020-08-12',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10040',
                'request_type' => 'Material Issuance',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(300)',
                'created_at' => '2020-08-05 10:07:50.080',
                'updated_at' => '2020-08-05 10:07:50.187',
                'net_value' => '7500',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => '2',
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10040',
            ),
            10 => 
            array (
                'id' => '10043',
                'priority' => 'High',
                'currency' => '14',
                'request_code' => 'MI0007',
                'status' => 'Awaiting User Reception',
                'due_date' => '2020-08-12',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10040',
                'request_type' => 'Material Issuance',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(300)',
                'created_at' => '2020-08-05 10:08:34.400',
                'updated_at' => '2020-08-05 10:08:34.510',
                'net_value' => '7500',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => '2',
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10040',
            ),
            11 => 
            array (
                'id' => '10044',
                'priority' => 'High',
                'currency' => '14',
                'request_code' => 'MI0008',
                'status' => 'Partially Issued',
                'due_date' => '2020-08-12',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10040',
                'request_type' => 'Material Issuance',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(300)',
                'created_at' => '2020-08-05 10:15:54.330',
                'updated_at' => '2020-08-05 10:17:44.623',
                'net_value' => '7500',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => '2',
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10040',
            ),
            12 => 
            array (
                'id' => '10045',
                'priority' => 'High',
                'currency' => '14',
                'request_code' => 'RFQ0012',
                'status' => 'RFQs sent out',
                'due_date' => '2020-08-12',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10040',
                'request_type' => 'Request for Quotation',
                'approval_count' => '1',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(300)',
                'created_at' => '2020-08-05 10:21:13.877',
                'updated_at' => '2020-08-05 10:22:05.023',
                'net_value' => '7500',
                'submission_deadline' => '1970-01-01 03:00:00.000',
                'supplier_id' => NULL,
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10040',
            ),
            13 => 
            array (
                'id' => '10046',
                'priority' => 'High',
                'currency' => '14',
                'request_code' => 'MI0009',
                'status' => 'In Preparation',
                'due_date' => '2020-08-12',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10040',
                'request_type' => 'Material Issuance',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(300)',
                'created_at' => '2020-08-05 10:21:14.277',
                'updated_at' => '2020-08-05 10:21:14.393',
                'net_value' => '7500',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => '2',
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10040',
            ),
            14 => 
            array (
                'id' => '10047',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'RFQ0013',
                'status' => 'Approval Complete',
                'due_date' => '2020-08-11',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10033',
                'request_type' => 'Request for Quotation',
                'approval_count' => '1',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(872), Fine Grain Sugar.(200), Brown Sugar(150), r1(123), r2(234)',
                'created_at' => '2020-08-05 10:22:53.217',
                'updated_at' => '2020-08-05 10:29:54.623',
                'net_value' => '91806',
                'submission_deadline' => '1970-01-01 03:00:00.000',
                'supplier_id' => NULL,
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10033',
            ),
            15 => 
            array (
                'id' => '10048',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'MI0010',
                'status' => 'In Preparation',
                'due_date' => '2020-08-11',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10033',
                'request_type' => 'Material Issuance',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(872), Fine Grain Sugar.(200), Brown Sugar(150), r1(123), r2(234)',
                'created_at' => '2020-08-05 10:22:53.953',
                'updated_at' => '2020-08-05 10:22:54.517',
                'net_value' => '91806',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => '7',
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10033',
            ),
            16 => 
            array (
                'id' => '10049',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'PO0010',
                'status' => 'Awaiting Approval',
                'due_date' => '2020-08-11',
                'parent_request' => 'Request for Quotation',
                'parent_request_id' => '10047',
                'request_type' => 'Purchase Orders',
                'approval_count' => '1',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Fine Grain Sugar.(200)',
                'created_at' => '2020-08-05 10:30:02.947',
                'updated_at' => '2020-08-05 10:30:03.380',
                'net_value' => '40000',
                'submission_deadline' => '1970-01-01 03:00:00.000',
                'supplier_id' => '2',
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10033',
            ),
            17 => 
            array (
                'id' => '10050',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'PO0011',
                'status' => 'Purchase Order Sent',
                'due_date' => '2020-08-11',
                'parent_request' => 'Request for Quotation',
                'parent_request_id' => '10047',
                'request_type' => 'Purchase Orders',
                'approval_count' => '1',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Brown Sugar(150)',
                'created_at' => '2020-08-05 10:30:03.533',
                'updated_at' => '2020-08-05 10:31:17.663',
                'net_value' => '39800',
                'submission_deadline' => '1970-01-01 03:00:00.000',
                'supplier_id' => '3',
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10033',
            ),
            18 => 
            array (
                'id' => '10051',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'GR0006',
                'status' => 'Completed',
                'due_date' => '2020-08-11',
                'parent_request' => 'Purchase Orders',
                'parent_request_id' => '10050',
                'request_type' => 'Goods Receipt',
                'approval_count' => '1',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Brown Sugar(150)',
                'created_at' => '2020-08-05 10:31:37.410',
                'updated_at' => '2020-08-05 10:32:20.240',
                'net_value' => '39800',
                'submission_deadline' => '1970-01-01 03:00:00.000',
                'supplier_id' => '3',
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10033',
            ),
            19 => 
            array (
                'id' => '10052',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'MI0011',
                'status' => 'Awaiting User Reception',
                'due_date' => '2020-08-11',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10033',
                'request_type' => 'Material Issuance',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(872), Fine Grain Sugar.(200), Brown Sugar(150), r1(123), r2(234)',
                'created_at' => '2020-08-05 10:41:31.577',
                'updated_at' => '2020-08-05 10:41:32.113',
                'net_value' => '91806',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => '7',
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10033',
            ),
            20 => 
            array (
                'id' => '10053',
                'priority' => 'High',
                'currency' => '14',
                'request_code' => 'MI0012',
                'status' => 'Awaiting User Reception',
                'due_date' => '2020-08-12',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10040',
                'request_type' => 'Material Issuance',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(300)',
                'created_at' => '2020-08-05 10:43:06.220',
                'updated_at' => '2020-08-05 10:43:06.310',
                'net_value' => '7500',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => '2',
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10040',
            ),
            21 => 
            array (
                'id' => '10054',
                'priority' => 'High',
                'currency' => '14',
                'request_code' => 'RFQ0014',
                'status' => 'Awarded',
                'due_date' => '2020-08-12',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10040',
                'request_type' => 'Request for Quotation',
                'approval_count' => '1',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(300)',
                'created_at' => '2020-08-05 10:43:39.087',
                'updated_at' => '2020-08-05 11:04:40.517',
                'net_value' => '47500',
                'submission_deadline' => '1970-01-01 03:00:00.000',
                'supplier_id' => NULL,
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10040',
            ),
            22 => 
            array (
                'id' => '10055',
                'priority' => 'High',
                'currency' => '14',
                'request_code' => 'MI0013',
                'status' => 'In Preparation',
                'due_date' => '2020-08-12',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10040',
                'request_type' => 'Material Issuance',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '2',
            'description' => 'Classical TestTubes(300)',
                'created_at' => '2020-08-05 10:43:39.387',
                'updated_at' => '2020-08-05 10:43:39.563',
                'net_value' => '7500',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => '2',
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10040',
            ),
            23 => 
            array (
                'id' => '10056',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'MR0020',
                'status' => 'Approval Complete',
                'due_date' => '2020-08-12',
                'parent_request' => NULL,
                'parent_request_id' => NULL,
                'request_type' => 'Material Requisition',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'Classical TestTubes(600), r2(200), Fine Grain Sugar.(5000)',
                'created_at' => '2020-08-05 12:07:52.413',
                'updated_at' => '2020-08-05 12:16:00.140',
                'net_value' => '1024000',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => NULL,
            ),
            24 => 
            array (
                'id' => '10057',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'RFQ0015',
                'status' => 'Approval Complete',
                'due_date' => '2020-08-12',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10056',
                'request_type' => 'Request for Quotation',
                'approval_count' => '1',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'Classical TestTubes(600), r2(200), Fine Grain Sugar.(5000)',
                'created_at' => '2020-08-05 12:17:09.857',
                'updated_at' => '2020-08-05 12:25:20.550',
                'net_value' => '1024000',
                'submission_deadline' => '1970-01-01 03:00:00.000',
                'supplier_id' => NULL,
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10056',
            ),
            25 => 
            array (
                'id' => '10058',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'MI0014',
                'status' => 'Completed',
                'due_date' => '2020-08-12',
                'parent_request' => 'Material Requisition',
                'parent_request_id' => '10056',
                'request_type' => 'Material Issuance',
                'approval_count' => '0',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'Classical TestTubes(600), r2(200), Fine Grain Sugar.(5000)',
                'created_at' => '2020-08-05 12:17:10.363',
                'updated_at' => '2020-08-05 12:42:27.773',
                'net_value' => '1024000',
                'submission_deadline' => NULL,
                'supplier_id' => NULL,
                'request_initiator' => '7',
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10056',
            ),
            26 => 
            array (
                'id' => '10059',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'PO0012',
                'status' => 'Purchase Order Sent',
                'due_date' => '2020-08-12',
                'parent_request' => 'Request for Quotation',
                'parent_request_id' => '10057',
                'request_type' => 'Purchase Orders',
                'approval_count' => '1',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'Fine Grain Sugar.(5000)',
                'created_at' => '2020-08-05 12:25:38.200',
                'updated_at' => '2020-08-05 12:27:00.480',
                'net_value' => '1000000',
                'submission_deadline' => '1970-01-01 03:00:00.000',
                'supplier_id' => '2',
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10056',
            ),
            27 => 
            array (
                'id' => '10060',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'PO0013',
                'status' => 'Purchase Order Sent',
                'due_date' => '2020-08-12',
                'parent_request' => 'Request for Quotation',
                'parent_request_id' => '10057',
                'request_type' => 'Purchase Orders',
                'approval_count' => '1',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'r2(200)',
                'created_at' => '2020-08-05 12:25:38.727',
                'updated_at' => '2020-08-05 12:40:14.550',
                'net_value' => '24000',
                'submission_deadline' => '1970-01-01 03:00:00.000',
                'supplier_id' => '3',
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10056',
            ),
            28 => 
            array (
                'id' => '10061',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'GR0007',
                'status' => 'Completed',
                'due_date' => '2020-08-12',
                'parent_request' => 'Purchase Orders',
                'parent_request_id' => '10059',
                'request_type' => 'Goods Receipt',
                'approval_count' => '1',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'Fine Grain Sugar.(5000)',
                'created_at' => '2020-08-05 12:28:36.293',
                'updated_at' => '2020-08-05 12:30:58.437',
                'net_value' => '1000000',
                'submission_deadline' => '1970-01-01 03:00:00.000',
                'supplier_id' => '2',
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10056',
            ),
            29 => 
            array (
                'id' => '10062',
                'priority' => 'Normal',
                'currency' => '14',
                'request_code' => 'GR0008',
                'status' => 'Completed',
                'due_date' => '2020-08-12',
                'parent_request' => 'Purchase Orders',
                'parent_request_id' => '10060',
                'request_type' => 'Goods Receipt',
                'approval_count' => '1',
                'required_approvals' => '1',
                'created_by' => '7',
            'description' => 'r2(200)',
                'created_at' => '2020-08-05 12:40:18.610',
                'updated_at' => '2020-08-05 12:41:14.183',
                'net_value' => '24000',
                'submission_deadline' => '1970-01-01 03:00:00.000',
                'supplier_id' => '3',
                'request_initiator' => NULL,
                'inventory_location_id' => '3',
                'parent_material_requisition' => '10056',
            ),
        ));
        
        
    }
}