<?php

use Illuminate\Database\Seeder;

class SampleHeadersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sample_headers')->delete();
        
        \DB::table('sample_headers')->insert(array (
            0 => 
            array (
                'id' => '30016',
                'batch_code' => 'BCCB00070020',
                'receipt_date' => '2020-07-13',
                'date_collected' => '2020-07-12',
                'crm_customer_id' => '4',
                'crm_unit_name' => 'Administration',
                'sample_type_id' => '10001',
                'reference_number' => 'RN 0789',
                'status' => 'Sample Approval',
                'is_routine' => '0',
                'routine_frequency' => '0.0',
                'created_at' => '2020-07-13 15:49:10.297',
                'updated_at' => '2020-07-19 21:32:35.590',
                'is_amendment' => NULL,
                'schedule_sent' => '0',
                'sample_tracking_stage' => '1',
                'description' => 'This is the description',
                'document_number' => 'XTG/678987/ER432',
                'importer_address' => '8543
Ronald Ngala',
                'receiving_officer' => '2',
                'sampling_officer' => '3',
                'priority' => 'High',
                'reason_for_submission' => '1,3,12',
                'how_sample_was_obtained' => NULL,
                'specialist_analyst_id' => '3',
                'declared_commodity_code' => NULL,
                'net_quantity_and_unit_of_quantity' => NULL,
                'sample_appearance_description' => NULL,
                'use_of_goods' => 'These are used goods.',
                'kra_office_ref' => NULL,
                'kra_office_station' => NULL,
                'where_sample_was_obtained' => NULL,
                'declared_amount' => '12345678',
                'final_declared_amount' => '987654321',
            ),
            1 => 
            array (
                'id' => '30017',
                'batch_code' => 'BCCB00070023',
                'receipt_date' => '2020-07-22',
                'date_collected' => '2020-07-21',
                'crm_customer_id' => '4',
                'crm_unit_name' => 'Administration',
                'sample_type_id' => '10001',
                'reference_number' => 'RN 0789',
                'status' => 'Samples In Lab',
                'is_routine' => '0',
                'routine_frequency' => '0.0',
                'created_at' => '2020-07-15 17:31:22.367',
                'updated_at' => '2020-07-21 16:08:33.177',
                'is_amendment' => NULL,
                'schedule_sent' => '0',
                'sample_tracking_stage' => '10008',
                'description' => 'This is a description',
                'document_number' => 'XTG/678987/ER432',
                'importer_address' => '1801 Excise Ave Suite 111',
                'receiving_officer' => '2',
                'sampling_officer' => '2',
                'priority' => 'Normal',
                'reason_for_submission' => '2,6',
                'how_sample_was_obtained' => NULL,
                'specialist_analyst_id' => '2',
                'declared_commodity_code' => NULL,
                'net_quantity_and_unit_of_quantity' => NULL,
                'sample_appearance_description' => NULL,
                'use_of_goods' => NULL,
                'kra_office_ref' => NULL,
                'kra_office_station' => NULL,
                'where_sample_was_obtained' => NULL,
                'declared_amount' => '1234567',
                'final_declared_amount' => '1345678',
            ),
            2 => 
            array (
                'id' => '30018',
                'batch_code' => 'BCCB00070024',
                'receipt_date' => '2020-07-15',
                'date_collected' => '2020-07-17',
                'crm_customer_id' => '4',
                'crm_unit_name' => 'Administration',
                'sample_type_id' => '10001',
                'reference_number' => 'XTG1234',
                'status' => 'Samples In Lab',
                'is_routine' => '0',
                'routine_frequency' => '0.0',
                'created_at' => '2020-07-16 14:33:41.883',
                'updated_at' => '2020-07-31 18:28:18.967',
                'is_amendment' => NULL,
                'schedule_sent' => '0',
                'sample_tracking_stage' => '1',
                'description' => 'This is a test',
                'document_number' => 'XTG/678987/ER432',
                'importer_address' => 'This is a test as well',
                'receiving_officer' => '2',
                'sampling_officer' => '1',
                'priority' => 'High',
                'reason_for_submission' => '2,3',
                'how_sample_was_obtained' => NULL,
                'specialist_analyst_id' => '3',
                'declared_commodity_code' => NULL,
                'net_quantity_and_unit_of_quantity' => NULL,
                'sample_appearance_description' => NULL,
                'use_of_goods' => NULL,
                'kra_office_ref' => NULL,
                'kra_office_station' => NULL,
                'where_sample_was_obtained' => NULL,
                'declared_amount' => '109876',
                'final_declared_amount' => '200000',
            ),
            3 => 
            array (
                'id' => '30021',
                'batch_code' => 'BCCB00070029',
                'receipt_date' => '2020-07-24',
                'date_collected' => '2020-07-25',
                'crm_customer_id' => '4',
                'crm_unit_name' => 'Administration',
                'sample_type_id' => '10001',
                'reference_number' => 'XZ200',
                'status' => 'Samples Reception',
                'is_routine' => '0',
                'routine_frequency' => '0.0',
                'created_at' => '2020-07-19 18:02:18.427',
                'updated_at' => '2020-07-19 19:42:23.037',
                'is_amendment' => NULL,
                'schedule_sent' => '0',
                'sample_tracking_stage' => '4',
                'description' => NULL,
                'document_number' => 'XTG/678987/ER432',
                'importer_address' => NULL,
                'receiving_officer' => NULL,
                'sampling_officer' => NULL,
                'priority' => 'Normal',
                'reason_for_submission' => NULL,
                'how_sample_was_obtained' => NULL,
                'specialist_analyst_id' => NULL,
                'declared_commodity_code' => NULL,
                'net_quantity_and_unit_of_quantity' => NULL,
                'sample_appearance_description' => NULL,
                'use_of_goods' => NULL,
                'kra_office_ref' => NULL,
                'kra_office_station' => NULL,
                'where_sample_was_obtained' => NULL,
                'declared_amount' => '0',
                'final_declared_amount' => NULL,
            ),
            4 => 
            array (
                'id' => '30022',
                'batch_code' => 'BCCB00070030',
                'receipt_date' => '2020-07-21',
                'date_collected' => '2020-07-20',
                'crm_customer_id' => '4',
                'crm_unit_name' => 'Administration',
                'sample_type_id' => '10001',
                'reference_number' => 'SD098',
                'status' => 'Samples Request Review',
                'is_routine' => '0',
                'routine_frequency' => '0.0',
                'created_at' => '2020-07-21 07:52:21.247',
                'updated_at' => '2020-07-25 18:19:27.610',
                'is_amendment' => NULL,
                'schedule_sent' => '0',
                'sample_tracking_stage' => '20007',
                'description' => NULL,
                'document_number' => 'XTG/678987/ER432',
                'importer_address' => NULL,
                'receiving_officer' => NULL,
                'sampling_officer' => NULL,
                'priority' => 'Normal',
                'reason_for_submission' => NULL,
                'how_sample_was_obtained' => NULL,
                'specialist_analyst_id' => NULL,
                'declared_commodity_code' => NULL,
                'net_quantity_and_unit_of_quantity' => NULL,
                'sample_appearance_description' => NULL,
                'use_of_goods' => NULL,
                'kra_office_ref' => NULL,
                'kra_office_station' => NULL,
                'where_sample_was_obtained' => NULL,
                'declared_amount' => '0',
                'final_declared_amount' => NULL,
            ),
            5 => 
            array (
                'id' => '30023',
                'batch_code' => 'BCCB00070031',
                'receipt_date' => '2020-07-20',
                'date_collected' => '2020-07-19',
                'crm_customer_id' => '4',
                'crm_unit_name' => 'Administration',
                'sample_type_id' => '10001',
                'reference_number' => 'RN 0879',
                'status' => 'Reports',
                'is_routine' => '0',
                'routine_frequency' => '0.0',
                'created_at' => '2020-07-21 12:44:16.310',
                'updated_at' => '2020-07-21 13:29:37.920',
                'is_amendment' => NULL,
                'schedule_sent' => '0',
                'sample_tracking_stage' => '10007',
                'description' => NULL,
                'document_number' => NULL,
                'importer_address' => NULL,
                'receiving_officer' => NULL,
                'sampling_officer' => NULL,
                'priority' => 'Normal',
                'reason_for_submission' => '2,3',
                'how_sample_was_obtained' => NULL,
                'specialist_analyst_id' => '3',
                'declared_commodity_code' => NULL,
                'net_quantity_and_unit_of_quantity' => NULL,
                'sample_appearance_description' => NULL,
                'use_of_goods' => NULL,
                'kra_office_ref' => NULL,
                'kra_office_station' => NULL,
                'where_sample_was_obtained' => NULL,
                'declared_amount' => '1234567',
                'final_declared_amount' => '2345678',
            ),
            6 => 
            array (
                'id' => '30024',
                'batch_code' => 'BCCB00070032',
                'receipt_date' => '2020-07-21',
                'date_collected' => '2020-07-20',
                'crm_customer_id' => '4',
                'crm_unit_name' => 'Administration',
                'sample_type_id' => '3',
                'reference_number' => '83939HJKJK',
                'status' => 'Samples In Lab',
                'is_routine' => '0',
                'routine_frequency' => '0.0',
                'created_at' => '2020-07-21 15:35:19.710',
                'updated_at' => '2020-07-26 18:16:28.493',
                'is_amendment' => NULL,
                'schedule_sent' => '0',
                'sample_tracking_stage' => '2',
                'description' => 'Fragile',
                'document_number' => 'XTG/678987/ER432',
                'importer_address' => '123',
                'receiving_officer' => '3',
                'sampling_officer' => '1',
                'priority' => 'High',
                'reason_for_submission' => '2',
                'how_sample_was_obtained' => NULL,
                'specialist_analyst_id' => '3',
                'declared_commodity_code' => NULL,
                'net_quantity_and_unit_of_quantity' => NULL,
                'sample_appearance_description' => NULL,
                'use_of_goods' => NULL,
                'kra_office_ref' => NULL,
                'kra_office_station' => NULL,
                'where_sample_was_obtained' => NULL,
                'declared_amount' => '0',
                'final_declared_amount' => NULL,
            ),
            7 => 
            array (
                'id' => '30025',
                'batch_code' => 'BCCB00070033',
                'receipt_date' => '2020-07-23',
                'date_collected' => '2020-07-22',
                'crm_customer_id' => '4',
                'crm_unit_name' => 'Administration',
                'sample_type_id' => '10001',
                'reference_number' => 'SAT78923',
                'status' => 'Samples Reception',
                'is_routine' => '0',
                'routine_frequency' => '0.0',
                'created_at' => '2020-07-23 19:24:41.073',
                'updated_at' => '2020-07-23 19:24:41.073',
                'is_amendment' => NULL,
                'schedule_sent' => '0',
                'sample_tracking_stage' => '4',
                'description' => NULL,
                'document_number' => NULL,
                'importer_address' => NULL,
                'receiving_officer' => NULL,
                'sampling_officer' => NULL,
                'priority' => 'Normal',
                'reason_for_submission' => NULL,
                'how_sample_was_obtained' => NULL,
                'specialist_analyst_id' => NULL,
                'declared_commodity_code' => NULL,
                'net_quantity_and_unit_of_quantity' => NULL,
                'sample_appearance_description' => NULL,
                'use_of_goods' => NULL,
                'kra_office_ref' => NULL,
                'kra_office_station' => NULL,
                'where_sample_was_obtained' => NULL,
                'declared_amount' => '0',
                'final_declared_amount' => NULL,
            ),
            8 => 
            array (
                'id' => '30026',
                'batch_code' => 'BCCB00070034',
                'receipt_date' => '2020-07-31',
                'date_collected' => '2020-08-05',
                'crm_customer_id' => '4',
                'crm_unit_name' => 'Administration',
                'sample_type_id' => '10001',
                'reference_number' => 'RN 0789',
                'status' => 'Sample Approval',
                'is_routine' => '0',
                'routine_frequency' => '0.0',
                'created_at' => '2020-08-05 09:50:48.017',
                'updated_at' => '2020-08-05 10:04:34.197',
                'is_amendment' => NULL,
                'schedule_sent' => '0',
                'sample_tracking_stage' => '1',
                'description' => NULL,
                'document_number' => NULL,
                'importer_address' => NULL,
                'receiving_officer' => NULL,
                'sampling_officer' => NULL,
                'priority' => 'High',
                'reason_for_submission' => '2',
                'how_sample_was_obtained' => NULL,
                'specialist_analyst_id' => '7',
                'declared_commodity_code' => NULL,
                'net_quantity_and_unit_of_quantity' => NULL,
                'sample_appearance_description' => NULL,
                'use_of_goods' => NULL,
                'kra_office_ref' => NULL,
                'kra_office_station' => NULL,
                'where_sample_was_obtained' => NULL,
                'declared_amount' => '0',
                'final_declared_amount' => NULL,
            ),
            9 => 
            array (
                'id' => '30027',
                'batch_code' => 'BCCB00070035',
                'receipt_date' => '2020-08-05',
                'date_collected' => '2020-08-04',
                'crm_customer_id' => '4',
                'crm_unit_name' => 'Administration',
                'sample_type_id' => '10001',
                'reference_number' => 'SAT-XTG-400',
                'status' => 'Samples Reception',
                'is_routine' => '0',
                'routine_frequency' => '0.0',
                'created_at' => '2020-08-05 11:11:28.410',
                'updated_at' => '2020-08-05 11:11:28.410',
                'is_amendment' => NULL,
                'schedule_sent' => '0',
                'sample_tracking_stage' => '4',
                'description' => NULL,
                'document_number' => NULL,
                'importer_address' => NULL,
                'receiving_officer' => NULL,
                'sampling_officer' => NULL,
                'priority' => 'Normal',
                'reason_for_submission' => NULL,
                'how_sample_was_obtained' => NULL,
                'specialist_analyst_id' => NULL,
                'declared_commodity_code' => NULL,
                'net_quantity_and_unit_of_quantity' => NULL,
                'sample_appearance_description' => NULL,
                'use_of_goods' => NULL,
                'kra_office_ref' => NULL,
                'kra_office_station' => NULL,
                'where_sample_was_obtained' => NULL,
                'declared_amount' => '0',
                'final_declared_amount' => NULL,
            ),
        ));
        
        
    }
}