<?php

use Illuminate\Database\Seeder;

class SampleDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sample_details')->delete();
        
        \DB::table('sample_details')->insert(array (
            0 => 
            array (
                'id' => '30030',
                'sample_code' => 'SAMP/000014',
                'analysis_type_id' => '10003',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-13 15:49:54.800',
                'updated_at' => '2020-07-19 21:23:22.843',
                'sample_header_id' => '30016',
                'sample_point_id' => '1',
                'company_product_id' => '4',
                'main_body' => '<p>This is Body Interpretations</p>',
                'header_body' => '<p>This is A Test too.</p>',
            ),
            1 => 
            array (
                'id' => '30031',
                'sample_code' => 'SAMP/000015',
                'analysis_type_id' => '4,5',
                'sample_condition_id' => '10007',
                'barcode' => NULL,
                'comments' => 'Something',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-13 15:49:54.853',
                'updated_at' => '2020-07-19 21:27:32.207',
                'sample_header_id' => '30016',
                'sample_point_id' => '4',
                'company_product_id' => '2',
                'main_body' => '<p>4</p>',
                'header_body' => '<p>2</p>',
            ),
            2 => 
            array (
                'id' => '30032',
                'sample_code' => 'SAMP/000016',
                'analysis_type_id' => '4',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => 'This is a comment',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-15 17:32:04.323',
                'updated_at' => '2020-07-15 17:32:04.323',
                'sample_header_id' => '30017',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            3 => 
            array (
                'id' => '30033',
                'sample_code' => 'SAMP/000017',
                'analysis_type_id' => '5',
                'sample_condition_id' => '10007',
                'barcode' => NULL,
                'comments' => 'This is a comment',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-15 17:39:24.167',
                'updated_at' => '2020-07-15 17:40:29.397',
                'sample_header_id' => '30017',
                'sample_point_id' => '4',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            4 => 
            array (
                'id' => '30034',
                'sample_code' => 'SAMP/000018',
                'analysis_type_id' => '5',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => 'This is a comment',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-15 17:39:24.237',
                'updated_at' => '2020-07-15 17:40:29.427',
                'sample_header_id' => '30017',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            5 => 
            array (
                'id' => '30035',
                'sample_code' => 'SAMP/000019',
                'analysis_type_id' => '4,5',
                'sample_condition_id' => '20006',
                'barcode' => NULL,
                'comments' => 'This is a comment',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-15 17:39:24.303',
                'updated_at' => '2020-07-15 17:40:29.447',
                'sample_header_id' => '30017',
                'sample_point_id' => '4',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            6 => 
            array (
                'id' => '30036',
                'sample_code' => 'SAMP/000020',
                'analysis_type_id' => '4',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => 'This is a comment',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-15 17:39:24.387',
                'updated_at' => '2020-07-15 17:39:24.387',
                'sample_header_id' => '30017',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            7 => 
            array (
                'id' => '30037',
                'sample_code' => 'SAMP/000021',
                'analysis_type_id' => '4',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => 'This is a comment',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-15 17:39:24.453',
                'updated_at' => '2020-07-15 17:39:24.453',
                'sample_header_id' => '30017',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            8 => 
            array (
                'id' => '30038',
                'sample_code' => 'SAMP/000022',
                'analysis_type_id' => '4',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => 'This is a comment',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-15 17:39:24.543',
                'updated_at' => '2020-07-15 17:39:24.543',
                'sample_header_id' => '30017',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            9 => 
            array (
                'id' => '30039',
                'sample_code' => 'SAMP/000023',
                'analysis_type_id' => '4',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => 'This is a comment',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-15 17:39:24.600',
                'updated_at' => '2020-07-15 17:39:24.600',
                'sample_header_id' => '30017',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            10 => 
            array (
                'id' => '30040',
                'sample_code' => 'SAMP/000024',
                'analysis_type_id' => '4',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => 'This is a comment',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-15 17:39:24.653',
                'updated_at' => '2020-07-15 17:39:24.653',
                'sample_header_id' => '30017',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            11 => 
            array (
                'id' => '30041',
                'sample_code' => 'SAMP/000025',
                'analysis_type_id' => '4',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => 'This is a comment',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-15 17:39:24.700',
                'updated_at' => '2020-07-15 17:39:24.700',
                'sample_header_id' => '30017',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            12 => 
            array (
                'id' => '30042',
                'sample_code' => 'SAMP/000026',
                'analysis_type_id' => '4',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => 'This is a comment',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-15 17:39:24.760',
                'updated_at' => '2020-07-15 17:39:24.760',
                'sample_header_id' => '30017',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            13 => 
            array (
                'id' => '30043',
                'sample_code' => 'SAMP/000027',
                'analysis_type_id' => '5',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-16 17:32:34.020',
                'updated_at' => '2020-07-27 04:13:52.500',
                'sample_header_id' => '30018',
                'sample_point_id' => '4',
                'company_product_id' => '4',
                'main_body' => '<p>This is the main body interpretations</p>',
                'header_body' => '<p>This is the report header body</p>',
            ),
            14 => 
            array (
                'id' => '30044',
                'sample_code' => 'SAMP/000028',
                'analysis_type_id' => '5',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-19 18:04:40.327',
                'updated_at' => '2020-07-19 18:04:40.327',
                'sample_header_id' => '30021',
                'sample_point_id' => '1',
                'company_product_id' => '4',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            15 => 
            array (
                'id' => '30045',
                'sample_code' => 'SAMP/000029',
                'analysis_type_id' => '5',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-19 19:42:46.287',
                'updated_at' => '2020-07-19 19:42:46.287',
                'sample_header_id' => '30021',
                'sample_point_id' => '1',
                'company_product_id' => '4',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            16 => 
            array (
                'id' => '30046',
                'sample_code' => 'SAMP/000030',
                'analysis_type_id' => '5',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => 'test',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-19 19:42:46.397',
                'updated_at' => '2020-07-19 19:43:10.350',
                'sample_header_id' => '30021',
                'sample_point_id' => '1',
                'company_product_id' => '4',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            17 => 
            array (
                'id' => '30047',
                'sample_code' => 'SAMP/000031',
                'analysis_type_id' => '5',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-19 19:42:46.517',
                'updated_at' => '2020-07-19 19:42:46.517',
                'sample_header_id' => '30021',
                'sample_point_id' => '1',
                'company_product_id' => '4',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            18 => 
            array (
                'id' => '30048',
                'sample_code' => 'SAMP/000032',
                'analysis_type_id' => '5',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-19 19:42:46.623',
                'updated_at' => '2020-07-19 19:42:46.623',
                'sample_header_id' => '30021',
                'sample_point_id' => '1',
                'company_product_id' => '4',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            19 => 
            array (
                'id' => '30049',
                'sample_code' => 'SAMP/000033',
                'analysis_type_id' => '4,5',
                'sample_condition_id' => '10007',
                'barcode' => NULL,
                'comments' => 'Important Goods',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-21 12:48:30.290',
                'updated_at' => '2020-07-21 13:24:16.500',
                'sample_header_id' => '30023',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => '<p>This is the main interpretation for this<strong> sample</strong></p>',
                'header_body' => '<p><span style="color: #e03e2d;"><strong>This is the header body information for this sample</strong></span></p>',
            ),
            20 => 
            array (
                'id' => '30050',
                'sample_code' => 'SAMP/000034',
                'analysis_type_id' => '4',
                'sample_condition_id' => '10007',
                'barcode' => NULL,
                'comments' => 'Important Goods',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-21 12:48:49.850',
                'updated_at' => '2020-07-21 12:48:49.850',
                'sample_header_id' => '30023',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            21 => 
            array (
                'id' => '30051',
                'sample_code' => 'SAMP/000035',
                'analysis_type_id' => '4',
                'sample_condition_id' => '10007',
                'barcode' => NULL,
                'comments' => 'Important Goods',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-21 12:48:49.960',
                'updated_at' => '2020-07-21 12:48:49.960',
                'sample_header_id' => '30023',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            22 => 
            array (
                'id' => '30052',
                'sample_code' => 'SAMP/000036',
                'analysis_type_id' => '10004',
                'sample_condition_id' => '20007',
                'barcode' => NULL,
                'comments' => 'Handle with care',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-21 15:39:21.423',
                'updated_at' => '2020-07-21 15:42:05.787',
                'sample_header_id' => '30024',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            23 => 
            array (
                'id' => '30053',
                'sample_code' => 'SAMP/000037',
                'analysis_type_id' => '10004',
                'sample_condition_id' => '20007',
                'barcode' => NULL,
                'comments' => 'Handle with care',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-21 15:40:18.490',
                'updated_at' => '2020-07-21 15:42:05.887',
                'sample_header_id' => '30024',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            24 => 
            array (
                'id' => '30054',
                'sample_code' => 'SAMP/000038',
                'analysis_type_id' => '10004',
                'sample_condition_id' => '20007',
                'barcode' => NULL,
                'comments' => 'Handle with care',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-21 15:40:18.587',
                'updated_at' => '2020-07-21 15:42:05.950',
                'sample_header_id' => '30024',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            25 => 
            array (
                'id' => '30055',
                'sample_code' => 'SAMP/000039',
                'analysis_type_id' => '10004',
                'sample_condition_id' => '20008',
                'barcode' => NULL,
                'comments' => 'Handle with care',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-21 15:40:18.703',
                'updated_at' => '2020-07-21 15:40:18.703',
                'sample_header_id' => '30024',
                'sample_point_id' => '1',
                'company_product_id' => '4',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            26 => 
            array (
                'id' => '30056',
                'sample_code' => 'SAMP/000040',
                'analysis_type_id' => '10004',
                'sample_condition_id' => '20008',
                'barcode' => NULL,
                'comments' => 'Handle with care',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-21 15:40:18.830',
                'updated_at' => '2020-07-21 15:40:18.830',
                'sample_header_id' => '30024',
                'sample_point_id' => '1',
                'company_product_id' => '4',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            27 => 
            array (
                'id' => '30057',
                'sample_code' => 'SAMP/000041',
                'analysis_type_id' => '10004',
                'sample_condition_id' => '20008',
                'barcode' => NULL,
                'comments' => 'Handle with care',
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-21 15:40:18.930',
                'updated_at' => '2020-07-21 15:40:18.930',
                'sample_header_id' => '30024',
                'sample_point_id' => '1',
                'company_product_id' => '4',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            28 => 
            array (
                'id' => '30074',
                'sample_code' => 'SAMP/000058',
                'analysis_type_id' => '5',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-24 14:23:05.087',
                'updated_at' => '2020-07-24 14:23:05.087',
                'sample_header_id' => '30022',
                'sample_point_id' => '4',
                'company_product_id' => '4',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            29 => 
            array (
                'id' => '30076',
                'sample_code' => 'SAMP/000061',
                'analysis_type_id' => '10003',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-26 18:30:05.577',
                'updated_at' => '2020-07-26 18:30:05.577',
                'sample_header_id' => '30025',
                'sample_point_id' => '4',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            30 => 
            array (
                'id' => '30077',
                'sample_code' => 'SAMP/000062',
                'analysis_type_id' => '10003',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-26 18:30:23.060',
                'updated_at' => '2020-07-26 18:30:23.060',
                'sample_header_id' => '30025',
                'sample_point_id' => '4',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            31 => 
            array (
                'id' => '30090',
                'sample_code' => 'SAMP/000075',
                'analysis_type_id' => '10003',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-27 02:53:16.037',
                'updated_at' => '2020-07-27 02:53:16.037',
                'sample_header_id' => '30025',
                'sample_point_id' => '4',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            32 => 
            array (
                'id' => '30091',
                'sample_code' => 'SAMP/000076',
                'analysis_type_id' => '10003',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-27 02:53:16.477',
                'updated_at' => '2020-07-27 02:53:16.477',
                'sample_header_id' => '30025',
                'sample_point_id' => '4',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            33 => 
            array (
                'id' => '30092',
                'sample_code' => 'SAMP/000077',
                'analysis_type_id' => '10003',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-27 02:53:16.917',
                'updated_at' => '2020-07-27 02:53:16.917',
                'sample_header_id' => '30025',
                'sample_point_id' => '4',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            34 => 
            array (
                'id' => '30093',
                'sample_code' => 'SAMP/000078',
                'analysis_type_id' => '10003',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-07-27 02:53:17.317',
                'updated_at' => '2020-07-27 02:53:17.317',
                'sample_header_id' => '30025',
                'sample_point_id' => '4',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            35 => 
            array (
                'id' => '30095',
                'sample_code' => 'SAMP/000080',
                'analysis_type_id' => '4,5,10003',
                'sample_condition_id' => '10006',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-08-05 09:52:04.820',
                'updated_at' => '2020-08-05 09:53:12.863',
                'sample_header_id' => '30026',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            36 => 
            array (
                'id' => '30096',
                'sample_code' => 'SAMP/000081',
                'analysis_type_id' => '10003',
                'sample_condition_id' => '10007',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-08-05 10:02:31.347',
                'updated_at' => '2020-08-05 10:02:31.347',
                'sample_header_id' => '30021',
                'sample_point_id' => '1',
                'company_product_id' => '4',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            37 => 
            array (
                'id' => '30102',
                'sample_code' => 'SAMP/000087',
                'analysis_type_id' => '4',
                'sample_condition_id' => '10007',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-08-05 11:15:27.693',
                'updated_at' => '2020-08-05 11:15:27.693',
                'sample_header_id' => '30027',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            38 => 
            array (
                'id' => '30103',
                'sample_code' => 'SAMP/000088',
                'analysis_type_id' => '4,5',
                'sample_condition_id' => '10007',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-08-05 11:16:34.250',
                'updated_at' => '2020-08-05 11:16:34.250',
                'sample_header_id' => '30027',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
            39 => 
            array (
                'id' => '30104',
                'sample_code' => 'SAMP/000089',
                'analysis_type_id' => '4,5',
                'sample_condition_id' => '10007',
                'barcode' => NULL,
                'comments' => NULL,
                'gps' => NULL,
                'photo_url' => NULL,
                'created_at' => '2020-08-05 11:16:34.717',
                'updated_at' => '2020-08-05 11:16:34.717',
                'sample_header_id' => '30027',
                'sample_point_id' => '1',
                'company_product_id' => '2',
                'main_body' => NULL,
                'header_body' => NULL,
            ),
        ));
        
        
    }
}