<?php

namespace App\Livewire\Crm\Complaint\Tabs;

use App\Models\CRM\Complaintattachment;
use Livewire\WithFileUploads;
use Livewire\Attributes\On;
use App\Livewire\Crm\BaseCrmComponent;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Auth;
use App\Exports\CRM\ComplaintTabExport;

class ComplaintAttachmentsTab extends BaseCrmComponent
{
    use WithFileUploads;

    public $complaintId;
    public $perPage = 10;
    public $attachmentFile;
    public $title = '';
    public $type = '';
    public $isPublic = false;
    public $description = '';
    public $customType = '';
    public $editingAttachmentId = null;
    public $attachmentIdToDelete = null;
    
    public $attachmentTypes = [
        'Supporting Document',
        'Evidence Photo',
        'Email Correspondence',
        'Customer Feedback',
    ];

    public $autoGeneratedTypes = [
        'Investigation Report',
        'Closure Report',
        'CAPA Report',
        'NCR Report',
        'Non-conformance',
        'CAPA',
        'Root Cause Analysis',
    ];

    public $availableAttachmentTypes = [];

    public function mount($complaintId)
    {
        $this->initialize();
        $this->complaintId = $complaintId;
        $this->loadAvailableAttachmentTypes();
    }

    public function loadAvailableAttachmentTypes()
    {
        $this->availableAttachmentTypes = \App\Models\CRM\ComplaintAttachmentType::where('is_system', false)
            ->pluck('name')
            ->toArray();
        
        sort($this->availableAttachmentTypes);
        $this->dispatch('attachment-types-updated');
    }

    public function getAttachmentsProperty()
    {
        return Complaintattachment::where('complaint_id', $this->complaintId)
            ->where('is_delete', '!=', 1)
            ->orderBy('id', 'desc')
            ->paginate($this->perPage);
    }

    public function exportToExcel()
    {
        $this->checkPermission('CRM.permission');
        return (new ComplaintTabExport($this->complaintId, 'attachments'))->download('complaint_attachments_' . now()->format('Ymd_His') . '.xlsx');
    }

    public function openAttachmentModal()
    {
        $this->reset(['title', 'type', 'customType', 'description', 'attachmentFile', 'isPublic', 'editingAttachmentId']);
        $this->dispatch('show-attachment-modal');
    }

    public function editAttachment($id)
    {
        $this->checkPermission('CRM.components.Complaints.Edit');
        
        $attachment = Complaintattachment::find($id);
        
        if ($attachment) {
            $this->editingAttachmentId = $attachment->id;
            $this->title = $attachment->title;
            
            if (in_array($attachment->type, $this->attachmentTypes) || !in_array($attachment->type, $this->autoGeneratedTypes)) {
                $this->type = $attachment->type;
                $this->customType = '';
            } else {
                $this->type = 'Add New Type';
                $this->customType = $attachment->type;
            }
            
            $this->description = $attachment->description;
            $this->isPublic = (bool)$attachment->is_public;
            
            // Ensure current attachment type is available in dropdown when editing
            if (in_array($attachment->type, $this->autoGeneratedTypes)) {
                $this->availableAttachmentTypes[] = $attachment->type;
                $this->availableAttachmentTypes = array_unique($this->availableAttachmentTypes);
                sort($this->availableAttachmentTypes);
            }
            
            $this->dispatch('show-attachment-modal');
        }
    }

    public function uploadAttachment()
    {
        $this->checkPermission('CRM.components.Complaints.Edit');
        
        $this->validate([
            'attachmentFile' => 'required|file|max:5120',
            'title' => 'required|string|max:255',
            'type' => 'required|string',
            'customType' => 'required_if:type,Add New Type|nullable|string|max:255',
        ]);

        $attachment = new Complaintattachment();
        $attachment->title = $this->title;
        if ($this->type === 'Add New Type' && $this->customType) {
            $attachment->type = $this->customType;
            // Persist the new type in the database for future use
            \App\Models\CRM\ComplaintAttachmentType::firstOrCreate(
                ['name' => $this->customType],
                ['is_system' => false]
            );
        } else {
            $attachment->type = $this->type;
        }
        $attachment->description = $this->description;
        $attachment->complaint_id = $this->complaintId;
        $attachment->posted_by = Auth::user()->name;
        $attachment->is_public = $this->isPublic;

        if ($this->attachmentFile) {
            $path = $this->attachmentFile->store('complaints', 'public');
            $fname = '/storage/' . $path;
            $attachment->file_path = $fname;
        }

        $attachment->save();

        $this->reset(['title', 'type', 'customType', 'description', 'attachmentFile', 'isPublic', 'editingAttachmentId']);
        $this->loadAvailableAttachmentTypes();
        
        $this->showSuccess('Attachment added successfully');
        $this->dispatch('close-attachment-modal');
        $this->dispatch('attachment-added');
    }

    public function updateAttachment()
    {
        $this->checkPermission('CRM.components.Complaints.Edit');
        
        $this->validate([
            'title' => 'required|string|max:255',
            'type' => 'required|string',
            'customType' => 'required_if:type,Add New Type|nullable|string|max:255',
            'attachmentFile' => 'nullable|file|max:5120', 
        ]);

        $attachment = Complaintattachment::find($this->editingAttachmentId);

        if (!$attachment) {
            return;
        }

        $attachment->title = $this->title;
        if ($this->type === 'Add New Type' && $this->customType) {
            $attachment->type = $this->customType;
            // Persist the new type in the database for future use
            \App\Models\CRM\ComplaintAttachmentType::firstOrCreate(
                ['name' => $this->customType],
                ['is_system' => false]
            );
        } else {
            $attachment->type = $this->type;
        }
        $attachment->description = $this->description;
        $attachment->is_public = $this->isPublic;

        if ($this->attachmentFile) {
            if ($attachment->file_path && Storage::disk('public')->exists(str_replace('/storage/', '', $attachment->file_path))) {
                Storage::disk('public')->delete(str_replace('/storage/', '', $attachment->file_path));
            }

            $path = $this->attachmentFile->store('complaints', 'public');
            $fname = '/storage/' . $path;
            $attachment->file_path = $fname;
        }

        $attachment->save();

        $this->reset(['title', 'type', 'customType', 'description', 'attachmentFile', 'isPublic', 'editingAttachmentId']);
        $this->loadAvailableAttachmentTypes();

        $this->showSuccess('Attachment updated successfully');
        $this->dispatch('close-attachment-modal');
        $this->dispatch('attachment-added');
    }

    public function confirmDelete($id)
    {
        $this->checkPermission('CRM.components.Complaints.Edit');
        $this->attachmentIdToDelete = $id;
        $this->dispatch('show-delete-confirmation');
    }

    public function deleteAttachment()
    {
        $this->checkPermission('CRM.components.Complaints.Edit');
        
        $attachment = Complaintattachment::find($this->attachmentIdToDelete);
        if ($attachment) {
            if ($attachment->file_path && Storage::disk('public')->exists(str_replace('/storage/', '', $attachment->file_path))) {
                Storage::disk('public')->delete(str_replace('/storage/', '', $attachment->file_path));
            }
            $attachment->is_delete = 1;
            $attachment->save();
            
            $this->showSuccess('Attachment deleted successfully');
            $this->dispatch('close-delete-confirmation');
            $this->dispatch('attachment-deleted');
            $this->attachmentIdToDelete = null;
        }
    }

    #[On('attachment-added')]
    #[On('attachment-deleted')]
    public function refreshAttachments()
    {
        $this->loadAvailableAttachmentTypes();
    }

    public function render()
    {
        return view('livewire.crm.complaint.tabs.complaint-attachments-tab', [
            'attachments' => $this->attachments,
        ]);
    }
}
