<?php

namespace App\Exports\Templates\Lab;

use App\Exports\Templates\ExcelTemplateGenerator;

class UnifiedLabHierarchyTemplateExporter extends ExcelTemplateGenerator
{
    protected function defineHeaders(): array
    {
        return [
            'sample_type_code*',
            'sample_type_name*',
            'is_results_attachable',
            'disposal_count',
            'analysis_type_code*',
            'analysis_type_name*',
            'lab_code*',
            'has_no_result',
            'reporting_time',
            'lab_section_code*',
            'equipment_code',
            'lod',
            'hod',
            'level',
            'method_sequence_name',
            'procedure_worksheet_name',
            'analyte_code*',
            'analyte_name*',
            'decimal_places',
            'reporting_symbol',
            'reporting_unit',
            'non_detectable',
            'non_accredited',
            'standard_code',
            'standard_name',
            'is_qc_standard',
            'qc_type',
            'standard_value_code',
            'standard_value_name',
            'standard_value_type',
            'standard_low',
            'standard_high',
            'standard_matrix_operator',
            'standard_value',
        ];
    }

    protected function defineExamples(): array
    {
        return [
            [
                'ST-WATER',
                'Water Material',
                '1',
                '30',
                'AT-POTABLE',
                'Potable Water Analysis',
                'LAB-01',
                '0',
                '2',
                'LS-PHYSCHEM',
                'EQ-PH01',
                '0.01',
                '14.0',
                'high',
                'SEQ-PH',
                'PROC-PH',
                'AN-PH',
                'pH Level',
                '2',
                'pH',
                'units',
                '0',
                '0',
                'STD-TBS-WATER',
                'TBS Potable Water Standard',
                '0',
                'chemical',
                'VAL-PH',
                'pH Limit',
                'range',
                '6.5',
                '8.5',
                '',
                '',
            ],
            [
                'ST-SOIL',
                'Soil Material',
                '1',
                '60',
                'AT-HEAVY-METALS',
                'Heavy Metals in Soil',
                'LAB-02',
                '0',
                '5',
                'LS-METALS',
                'EQ-ICP01',
                '0.001',
                '1000.0',
                'low',
                '',
                '',
                'AN-PB',
                'Lead Level',
                '4',
                'Pb',
                'mg/kg',
                '1',
                '0',
                'STD-WHO-SOIL',
                'WHO Soil Quality Standard',
                '0',
                'heavy_metals',
                'VAL-PB',
                'Lead Max Limit',
                'use_value',
                '',
                '',
                'max',
                '0.05',
            ],
        ];
    }
}
