<?php

namespace App\Exports\Templates\Lab;

use App\Exports\Templates\ExcelTemplateGenerator;

class UnifiedLabHierarchyTemplateExporter extends ExcelTemplateGenerator
{
    protected function defineHeaders(): array
    {
        return [
            'sample_type_code*',
            'sample_type_name*',
            'is_results_attachable',
            'disposal_count',
            'analysis_type_code*',
            'analysis_type_name*',
            'lab_code*',
            'has_no_result',
            'reporting_time',
            'lab_section_code*',
            'equipment_code',
            'equipment',
            'lod',
            'loq',
            'level',
            'method',
            'method_sequence_name',
            'procedure_worksheet_name',
            'analyte_code',
            'analyte_name*',
            'decimal_places',
            'reporting_symbol',
            'reporting_unit',
            'non_detectable',
            'non_accredited',
            'standard_code',
            'standard_name',
            'is_qc_standard',
            'qc_type',
            'standard_value_code',
            'standard_value_name',
            'standard_value_type',
            'standard_low',
            'standard_high',
            'standard_matrix_operator',
            'standard_value',
        ];
    }

    protected function defineExamples(): array
    {
        return [
            [
                'Food & Feed',
                'Food & Feed',
                '1',
                '30',
                'General Foods',
                'General Foods',
                'AMSPEC',
                '0',
                '',
                'Microbiology',
                '',
                '',
                '',
                '10',
                '',
                'ISO 4833-1',
                '',
                '',
                '',
                'Mesophilic Aerobic Plate Count in Food Samples',
                '1',
                '',
                'CFU/g',
                '0',
                'No',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
            ],
            [
                'Food & Feed',
                'Food & Feed',
                '1',
                '30',
                'Dairy',
                'Dairy',
                'AMSPEC',
                '0',
                '',
                'Microbiology',
                '',
                '',
                '',
                '10',
                '',
                'ISO 4833-1',
                '',
                '',
                '',
                'Mesophilic Aerobic Plate Count in Food Samples',
                '1',
                '',
                'CFU/g',
                '0',
                'No',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
            ],
            [
                'ST-WATER',
                'Water Material',
                '1',
                '30',
                'AT-POTABLE',
                'Potable Water Analysis',
                'LAB-01',
                '0',
                '2',
                'LS-PHYSCHEM',
                'EQ-PH01',
                'pH Meter',
                '0.01',
                '0.05',
                'high',
                'Electrometric Method',
                'SEQ-PH',
                'PROC-PH',
                'AN-PH',
                'pH Level',
                '2',
                'pH',
                'units',
                '0',
                '0',
                'STD-TBS-WATER',
                'TBS Potable Water Standard',
                '0',
                'chemical',
                'VAL-PH',
                'pH Limit',
                'range',
                '6.5',
                '8.5',
                '',
                '',
            ],
        ];
    }
}
