<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbaac400caf3433e1bcd483c036691587
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPJasper\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPJasper\\' => 
        array (
            0 => __DIR__ . '/..' . '/geekcom/phpjasper/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbaac400caf3433e1bcd483c036691587::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbaac400caf3433e1bcd483c036691587::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
