[group:imara-ai]
programs=ai-api,ai-worker,ai-beat

[program:ai-api]
command=/home/andy/Desktop/Projects/nuvemite/polucon/scripts/run_inference.sh
directory=/home/andy/Desktop/Projects/nuvemite/polucon/python
autostart=true
autorestart=true
stderr_logfile=/home/andy/Desktop/Projects/nuvemite/polucon/python/ai_service/uvicorn.err.log
stdout_logfile=/home/andy/Desktop/Projects/nuvemite/polucon/python/ai_service/uvicorn.out.log
environment=PYTHONPATH="/home/andy/Desktop/Projects/nuvemite/polucon/python"

[program:ai-worker]
command=/home/andy/Desktop/Projects/nuvemite/polucon/scripts/run_worker.sh
directory=/home/andy/Desktop/Projects/nuvemite/polucon/python
autostart=true
autorestart=true
stderr_logfile=/home/andy/Desktop/Projects/nuvemite/polucon/python/ai_service/worker.err.log
stdout_logfile=/home/andy/Desktop/Projects/nuvemite/polucon/python/ai_service/worker.out.log
environment=PYTHONPATH="/home/andy/Desktop/Projects/nuvemite/polucon/python"

[program:ai-beat]
command=/home/andy/Desktop/Projects/nuvemite/polucon/scripts/run_beat.sh
directory=/home/andy/Desktop/Projects/nuvemite/polucon/python
autostart=true
autorestart=true
stderr_logfile=/home/andy/Desktop/Projects/nuvemite/polucon/python/ai_service/beat.err.log
stdout_logfile=/home/andy/Desktop/Projects/nuvemite/polucon/python/ai_service/beat.out.log
environment=PYTHONPATH="/home/andy/Desktop/Projects/nuvemite/polucon/python"
